[package]
name = "microbit-1"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"

[[bin]]
name = "microbit-1"
path = "src/main.rs"
test = false
doctest = false
bench = false
